branches:
  only:
    - master

language: node_js
node_js:
  - lts/*
cache:
  directories:
    - node_modules

install:
  - git clone https://github.com/${GIT_URI}.git ../super/
  - mv ./* ../super/${FOLDER_SOURCE}/
  - cd ../super/
  - npm install
script:
  - npm run build
deploy:
  provider: pages
  on:
    branch: master
  skip_cleanup: true
  local_dir: ../super/${FOLDER_TARGET}
  fqdn: ${DOMAIN}
  repo: ${GIT_URI}
  target_branch: ${BRANCH}
  token: ${TOKEN}
