name: CI & CD
on:
    push:
        branches:
            - master
jobs:
    Build-and-Deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Data repository
              uses: actions/checkout@v3
              with:
                  lfs: true
            - name: Checkout Program repository
              uses: actions/checkout@v3
              with:
                  repository: ${{ secrets.GIT_URI }}
                  ref: hexo
                  path: super/
            - name: Merge Data & Program
              run: |
                  shopt -s extglob
                  mv !(super) super/source/
                  mv super/* .
            - uses: pnpm/action-setup@v2
              with:
                  version: 7
            - uses: actions/setup-node@v3
              with:
                  node-version: 14
                  cache: pnpm
            - name: Install Dependencies
              run: pnpm i --frozen-lockfile

            - name: Build Production
              run: pnpm build

            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              with:
                  publish_dir: ./public
                  cname: kaiyuanshe.cn
                  external_repository: ${{ secrets.GIT_URI }}
                  publish_branch: master
                  personal_token: ${{ secrets.PERSONAL_TOKEN }}
                  force_orphan: true
